steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - api-to-gcs
  - --region=us-central1
  - --entry-point=api_to_gcs
  - --source=./data_extraction/api_to_gcs
  - --trigger-http
  - --runtime=python39
  - --timeout=540s
  - --memory=2Gi
  - --set-secrets=API_KEY=API_KEY:latest
options:
  logging: 'CLOUD_LOGGING_ONLY'