steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - traffic
  - --region=us-central1
  - --entry-point=traffic
  - --source=./data_extraction/traffic
  - --trigger-http
  - --runtime=python39
  - --timeout=540s
  - --memory=2Gi
  - --set-secrets=DB_HOSTNAME=DB_HOSTNAME:latest
  - --set-secrets=DB_USERNAME=DB_USERNAME:latest
  - --set-secrets=DB_PASSWORD=DB_PASSWORD:latest
  - --set-secrets=API_KEY=API_KEY:latest
options:
  logging: 'CLOUD_LOGGING_ONLY'